### ISSUE TITLE
KCV can't get data form game due to Nekoxy-fiddler

### ISSUE THREAD

**Issue by Explorare** [Gizeta/Nekoxy-fiddler#1]
System Environment:
Windows 8.1 x64
KanColleViewer v4.1.3
Nekoxy-fiddler v1.5.1r2
KanColleCacher v2.3.0.38

KCV can't get data after applied the patch.Like this
![Poi](https://hime.io/images/2015/09/04/9016758566657750.jpg)

Help please.
Thanks

**Comment by xiuluo** [comment]
而且，在无法获取api的情况下，运行kcv一段时间后，kcv会突然崩溃。

**Comment by Gizeta** [comment]
@xiuluo 
崩溃的话，error.log有没有什么记录？

**Comment by xiuluo** [comment]
# @Gizeta 

ERROR, date = 2015/9/2 星期三 22:40:56 +08:00, sender = 名称:KanColleViewer.exe
无上下文策略。
,
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Grabacr07.KanColleViewer.Models.NotifyService.HandleRepairyardCompleted(Object sender, RepairingCompletedEventArgs args)
   在 Grabacr07.KanColleWrapper.Models.RepairingDock.Tick()
   在 Grabacr07.KanColleWrapper.TimerNotifier.<.ctor>b__3_0(Int64 _)
   在 System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   在 System.Reactive.ObserverBase`1.OnNext(T value)
   在 System.Reactive.Observer`1.OnNext(T value)
   在 System.Reactive.Subjects.Subject`1.OnNext(T value)
   在 System.Reactive.Linq.ObservableImpl.AsObservable`1._.OnNext(TSource value)
   在 System.Reactive.Linq.ObservableImpl.Timer.TimerImpl.Tock(Int64 count)
   在 System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<SchedulePeriodic>b__7()
   在 System.Reactive.Concurrency.AsyncLock.Wait(Action action)
   在 System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<SchedulePeriodic>b__6()
   在 System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.PeriodicTimer.Tick(Object state)
   在 System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.TimerQueueTimer.CallCallback()
   在 System.Threading.TimerQueueTimer.Fire()
   在 System.Threading.TimerQueue.FireNextTimers()
   在 System.Threading.TimerQueue.AppDomainTimerCallback()

# 

ERROR, date = 2015/9/3 星期四 19:09:48 +08:00, sender = 名称:KanColleViewer.exe
无上下文策略。
,
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Grabacr07.KanColleViewer.Models.NotifyService.HandleRepairyardCompleted(Object sender, RepairingCompletedEventArgs args)
   在 Grabacr07.KanColleWrapper.Models.RepairingDock.Tick()
   在 Grabacr07.KanColleWrapper.TimerNotifier.<.ctor>b__3_0(Int64 _)
   在 System.Reactive.AnonymousObserver`1.OnNextCore(T value)
   在 System.Reactive.ObserverBase`1.OnNext(T value)
   在 System.Reactive.Observer`1.OnNext(T value)
   在 System.Reactive.Subjects.Subject`1.OnNext(T value)
   在 System.Reactive.Linq.ObservableImpl.AsObservable`1._.OnNext(TSource value)
   在 System.Reactive.Linq.ObservableImpl.Timer.TimerImpl.Tock(Int64 count)
   在 System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<SchedulePeriodic>b__7()
   在 System.Reactive.Concurrency.AsyncLock.Wait(Action action)
   在 System.Reactive.Concurrency.DefaultScheduler.<>c__DisplayClass9`1.<SchedulePeriodic>b__6()
   在 System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.PeriodicTimer.Tick(Object state)
   在 System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.TimerQueueTimer.CallCallback()
   在 System.Threading.TimerQueueTimer.Fire()
   在 System.Threading.TimerQueue.FireNextTimers()
   在 System.Threading.TimerQueue.AppDomainTimerCallback()

**Comment by Explorare** [comment]
实测采用更新后，导致出击时100%卡在选择阵型之后，无法进入战斗，移除KanColleCacher后问题消失。求解决。

**Comment by Gizeta** [comment]
选阵型之后是加载swf，是不是在下载缓存？

**Comment by Explorare** [comment]
不知道啊，可是禁用插件之后，大概等两秒就能进入战斗了，而是用插件会无限卡下去。
