### ISSUE TITLE
替换之后kcv无法运行

### ISSUE THREAD

**Issue by xiuluo** [Gizeta/Nekoxy-fiddler#2]
![20150909145351](https://cloud.githubusercontent.com/assets/2190708/9755219/d4578a04-5702-11e5-88e4-69106c9306f0.png)

**Comment by Gizeta** [comment]
下载的dll文件是否都解锁了？
dll文件是否放在kcv目录下（替换原有的Nekoxy和TrotiNet）？

**Comment by xiuluo** [comment]
解锁了，也全放在了KanColleViewer.exe所在目录
